# Site settings
# Remove minima theme and blog defaults
# theme: minima
# Remove default collections and feed
# plugins:
#   - jekyll-feed

# Add custom pages collection
collections:
  pages:
    output: true
    permalink: /:name/

# General site info
url: ""
title: "MTZ Landscape & Irrigation Systems LLC"
description: "Professional landscaping and gardening services"
keywords: "gardening, landscaping, garden services"

# Exclude default files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - _posts
  - about.markdown
  - index.markdown

# Permalinks
permalink: pretty
